/**
 * Shared HTML sanitizer for markdown content
 * 
 * This utility provides consistent HTML sanitization across all components
 * that render markdown content. It prevents XSS attacks by:
 * - Removing disallowed HTML tags
 * - Removing disallowed attributes
 * - Removing all event handlers (on*)
 * - Validating href schemes on anchor tags (only allows https?, mailto:, #, /)
 * 
 * Usage:
 *   import { sanitizeMarkdownHtml } from '../utils/sanitizeMarkdownHtml';
 *   const safeHtml = sanitizeMarkdownHtml(marked.parse(text));
 */
import { marked } from 'marked';

// Allowed HTML tags for markdown rendering
export const ALLOWED_TAGS = new Set([
  'a', 'blockquote', 'br', 'code', 'del', 'em', 'h1', 'h2', 'h3', 'h4',
  'h5', 'h6', 'hr', 'li', 'ol', 'p', 'pre', 'strong', 'table', 'tbody',
  'td', 'th', 'thead', 'tr', 'ul', 'sup', 'sub', 'span', 'img',
]);

// Allowed attributes per tag
// NOTE: 'style' has been intentionally removed from <span> to prevent CSS-based
// information exfiltration and misleading layout attacks (security audit L-1).
// <img> is allowed so that images generated by Leanna (data-URI PNG/JPEG) render
// inline in the chat. Its 'src' is restricted by isSafeImageSrc (data:image/* and
// relative paths only — never javascript:, and never arbitrary external hosts).
export const ALLOWED_ATTRIBUTES: Record<string, Set<string>> = {
  a: new Set(['href', 'title']),
  code: new Set(['class']),
  span: new Set(['class']),
  img: new Set(['src', 'alt', 'title', 'width', 'height']),
};

/**
 * Validates that a URL scheme is safe for use in href attributes.
 * Only allows: https?, mailto:, relative paths (/), and hash fragments (#)
 * Explicitly blocks: javascript:, data:, vbscript:, and other dangerous schemes
 *
 * SECURITY FIX: Browsers strip ASCII tab (\t), newline (\n) and carriage-return (\r)
 * characters from a URL *before* resolving its scheme. A naive prefix check like
 * `value.startsWith('javascript:')` can therefore be bypassed with a payload such as
 * `"java\tscript:alert(1)"`, which the string comparison sees as a harmless value but
 * which the browser resolves and executes as `javascript:alert(1)`. We strip those
 * characters first so the check can't be evaded this way.
 */
function isSafeHref(value: string): boolean {
  // Normalize away characters browsers ignore when parsing a URL scheme.
  const normalized = value.replace(/[\t\n\r]/g, '');

  // Test against safe schemes
  const safeSchemePattern = /^(https?:|mailto:|#|\/)/i;
  if (safeSchemePattern.test(normalized)) {
    return true;
  }

  // Explicitly block dangerous schemes
  const dangerousSchemes = ['javascript:', 'data:', 'vbscript:', 'file:', 'about:'];
  const lowerValue = normalized.toLowerCase();
  for (const scheme of dangerousSchemes) {
    if (lowerValue.startsWith(scheme)) {
      return false;
    }
  }

  // If no scheme is present (relative URL), allow it
  // This handles cases like "path/to/page" or "./file.html"
  if (!normalized.includes(':')) {
    return true;
  }

  // Default: deny
  return false;
}

/**
 * Validates that an <img> src is safe.
 *
 * Only two shapes are permitted:
 *   1. Inline images encoded as `data:image/<type>;base64,...` — this is how
 *      Leanna returns generated images so they can render inline in the chat
 *      without an extra network round-trip.
 *   2. Relative paths (no scheme) — e.g. `generated-images/foo.png`, resolved
 *      against the app origin.
 *
 * Everything else is rejected, including `javascript:`/`vbscript:` (XSS),
 * non-image `data:` payloads, and absolute `http(s)`/`file:` URLs (which would
 * allow silent exfiltration or loading of arbitrary remote content).
 *
 * As with isSafeHref, characters browsers strip before scheme resolution
 * (\t, \n, \r) are normalized away first so the check cannot be bypassed.
 */
function isSafeImageSrc(value: string): boolean {
  const normalized = value.replace(/[\t\n\r]/g, '').trim();

  // Inline base64 image data-URI only (raster image/* media types).
  // SVG is intentionally excluded: `data:image/svg+xml` can embed <script> and
  // would be an XSS vector. Leanna's generator only emits raster formats.
  if (/^data:image\/(png|jpeg|jpg|gif|webp);base64,[a-z0-9+/=\s]+$/i.test(normalized)) {
    return true;
  }

  // Reject any other scheme (data:text/html, javascript:, http:, file:, ...).
  // A relative path has no scheme before the first '/' or is purely relative.
  const lower = normalized.toLowerCase();
  const dangerousSchemes = ['javascript:', 'vbscript:', 'data:', 'file:', 'about:', 'http:', 'https:'];
  for (const scheme of dangerousSchemes) {
    if (lower.startsWith(scheme)) {
      return false;
    }
  }

  // Allow scheme-less relative references only.
  if (!normalized.includes(':')) {
    return true;
  }

  return false;
}

/**
 * Sanitizes HTML from markdown parsing to prevent XSS attacks.
 * 
 * @param html - The HTML string to sanitize (typically output from marked.parse)
 * @returns A safe HTML string with disallowed tags/attributes removed
 */
export function sanitizeMarkdownHtml(html: string): string {
  if (!html || typeof html !== 'string') {
    return '';
  }

  // Create a template element to parse the HTML
  const template = document.createElement('template');
  template.innerHTML = html;

  // Process all elements in the parsed HTML
  for (const element of Array.from(template.content.querySelectorAll('*'))) {
    const tagName = element.tagName.toLowerCase();

    // Remove disallowed tags, keeping their children
    if (!ALLOWED_TAGS.has(tagName)) {
      element.replaceWith(...Array.from(element.childNodes));
      continue;
    }

    // Process attributes for allowed tags
    const allowedAttributes = ALLOWED_ATTRIBUTES[tagName] ?? new Set<string>();
    for (const attribute of Array.from(element.attributes)) {
      const name = attribute.name.toLowerCase();
      const value = attribute.value.trim();

      // Remove any attribute that is not allowed or is an event handler
      if (!allowedAttributes.has(name) || name.startsWith('on')) {
        element.removeAttribute(attribute.name);
        continue;
      }

      // Special handling for href attributes on anchor tags
      if (tagName === 'a' && name === 'href') {
        if (!isSafeHref(value)) {
          element.removeAttribute(attribute.name);
        }
      }

      // Special handling for src on <img>: only data:image/* or relative paths.
      if (tagName === 'img' && name === 'src') {
        if (!isSafeImageSrc(value)) {
          element.removeAttribute(attribute.name);
        }
      }
    }

    // Drop <img> that lost its src during sanitization (nothing to render).
    if (tagName === 'img' && !element.getAttribute('src')) {
      element.remove();
      continue;
    }
  }

  // Add security attributes to all anchor tags
  for (const link of Array.from(template.content.querySelectorAll('a[href]'))) {
    link.setAttribute('rel', 'noopener noreferrer');
    link.setAttribute('target', '_blank');
  }

  // Constrain rendered images so a large generated image stays inside the chat
  // bubble, and defer offscreen decoding.
  for (const img of Array.from(template.content.querySelectorAll('img'))) {
    img.setAttribute('loading', 'lazy');
    img.setAttribute('decoding', 'async');
    const cls = img.getAttribute('class');
    img.setAttribute('class', cls ? `${cls} chat-generated-image` : 'chat-generated-image');
  }

  return template.innerHTML;
}

/**
 * Sanitizes and parses markdown content in one step.
 * This is a convenience function that combines marked.parse with sanitization.
 * 
 * @param markdown - The markdown text to parse and sanitize
 * @param options - Options to pass to marked.parse
 * @returns A safe HTML string
 */
export function safeMarkdownParse(markdown: string, options?: Parameters<typeof marked.parse>[1]): string {
  try {
    const html = marked.parse(markdown, options);
    return typeof html === 'string' ? sanitizeMarkdownHtml(html) : '';
  } catch {
    // If parsing fails, escape the original content as plain text
    const escaped = String(markdown)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
    return `<p>${escaped}</p>`;
  }
}